backend:
  name: git-gateway
  branch: main

# Pro lokální testování bez Netlify můžete použít:
# backend:
#   name: test-repo

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "hlavni-stranka"
    label: "Hlavní stránka"
    files:
      - name: "popup"
        label: "Popup na hlavní stránce"
        file: "content/popup.md"
        fields:
          - {label: "Aktivní", name: "active", widget: "boolean", default: false}
          - {label: "Nadpis", name: "title", widget: "string"}
          - {label: "Obsah", name: "body", widget: "markdown"}

  - name: "pracovnici"
    label: "Pracovníci"
    folder: "content/kolektiv"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Jméno", name: "title", widget: "string"}
      - {label: "Pozice", name: "position", widget: "string"}
      - {label: "Pořadí", name: "weight", widget: "number", default: 100}
      - {label: "Fotografie", name: "image", widget: "image"}
      - {label: "Popis", name: "body", widget: "markdown"}