backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "hlavni-stranka"
    label: "Hlavní stránka"
    files:
      - name: "popup"
        label: "Popup na hlavní stránce"
        file: "content/popup.md"
        fields:
          - {label: "Aktivní", name: "active", widget: "boolean", default: false}
          - {label: "Nadpis", name: "title", widget: "string"}
          - {label: "Obsah", name: "body", widget: "markdown"}

  - name: "pracovnici"
    label: "Pracovníci"
    folder: "content/kolektiv"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Jméno", name: "title", widget: "string"}
      - {label: "Pozice", name: "position", widget: "string"}
      - {label: "Pořadí", name: "weight", widget: "number", default: 100}
      - {label: "Fotografie", name: "image", widget: "image"}
      - {label: "Popis", name: "body", widget: "markdown"}

  - name: "aktuality"
    label: "Aktuality"
    folder: "content/aktuality"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Datum publikování", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Popis pro SEO", name: "description", widget: "text", required: false}
      - {label: "Obsah", name: "body", widget: "markdown"}
      - {label: "Obrázek", name: "image", widget: "image", required: false}

  - name: "rozpis-sluzeb"
    label: "Rozpis služeb"
    files:
      - name: "sluzby"
        label: "Rozpis služeb"
        file: "data/sluzby.json"
        fields:
          - label: "Dny"
            name: "body"
            widget: "list"
            fields:
              - {label: "Den", name: "den", widget: "string"}
              - label: "Doktoři"
                name: "doktori"
                widget: "list"
                field: {label: "Doktor", widget: "string"}
